export const FETCH_PRODUCTS_LOADING = "FETCH_PRODUCTS_LOADING";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const SELECTED_PRODUCT_LOADING = "SELECTED_PRODUCT_LOADING";
export const SELECTED_PRODUCT_SUCCESS = "SELECTED_PRODUCT_SUCCESS";
export const SELECTED_PRODUCT_FAILURE = "SELECTED_PRODUCT_FAILURE";

export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const LOAD_WISHLIST = "LOAD_WISHLIST";

export const CATEGORY_TYPE_LOADING = "CATEGORY_TYPE_LOADING";
export const CATEGORY_TYPE_SUCCESS = "CATEGORY_TYPE_SUCCESS";
export const CATEGORY_TYPE_FAILURE = "CATEGORY_TYPE_FAILURE";

export const CATEGORYLIST_SUCCESS = "CATEGORYLIST_SUCCESS";

