export const FETCH_PRODUCTS_LOADING = "FETCH_PRODUCTS_LOADING";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const SELECTED_PRODUCT_LOADING = "SELECTED_PRODUCT_LOADING";
export const SELECTED_PRODUCT_SUCCESS = "SELECTED_PRODUCT_SUCCESS";
export const SELECTED_PRODUCT_FAILURE = "SELECTED_PRODUCT_FAILURE";

export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";

export const CATEGORY_TYPE_LOADING = "CATEGORY_TYPE_LOADING";
export const CATEGORY_TYPE_SUCCESS = "CATEGORY_TYPE_SUCCESS";
export const CATEGORY_TYPE_FAILURE = "CATEGORY_TYPE_FAILURE";

export const CATEGORYLIST_SUCCESS = "CATEGORYLIST_SUCCESS";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_ITEM_INCREASE_QUANTITY = "CART_ITEM_INCREASE_QUANTITY";
export const CART_ITEM_DECREASE_QUANTITY = "CART_ITEM_DECREASE_QUANTITY";
export const CART_TOTAL_AMOUNT = "CART_TOTAL_AMOUNT";
